/* tslint:disable */
/* eslint-disable */
/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/imports-api';
export * from './api/leave-requests-api';
export * from './api/leaves-api';

