/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ImportsApi,
  LeaveRequestsApi,
  LeavesApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { LuccaTimmiAbsencesCustom } from "./client-custom";

export class LuccaTimmiAbsences extends LuccaTimmiAbsencesCustom {
  readonly imports: ImportsApi;
  readonly leaveRequests: LeaveRequestsApi;
  readonly leaves: LeavesApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.imports = new ImportsApi(configuration);
    this.leaveRequests = new LeaveRequestsApi(configuration);
    this.leaves = new LeavesApi(configuration);
  }

}
