/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * ## Fields
 * @export
 * @interface CancellationRequest
 */
export interface CancellationRequest {
    /**
     * 
     * @type {number}
     * @memberof CancellationRequest
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof CancellationRequest
     */
    'authorId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CancellationRequest
     */
    'comment'?: string;
    /**
     * 0 = PENDING_APPROVAL  2 = APPROVED  3 = DENIED  4 = CANCELLED  5 = CANCELLATION_PENDING 
     * @type {number}
     * @memberof CancellationRequest
     */
    'rank'?: CancellationRequestRankEnum;
    /**
     * 
     * @type {boolean}
     * @memberof CancellationRequest
     */
    'approved'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CancellationRequest
     */
    'creationDate'?: string;
    /**
     * 
     * @type {any}
     * @memberof CancellationRequest
     */
    'nextApproverId'?: any;
    /**
     * 
     * @type {boolean}
     * @memberof CancellationRequest
     */
    'isActive'?: boolean;
}

type CancellationRequestRankEnum = 0 | 2 | 3 | 4 | 5


