/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ImportsAbsenceBatchCreateResponseDataReport } from './imports-absence-batch-create-response-data-report';

/**
 * 
 * @export
 * @interface ImportsAbsenceBatchCreateResponseData
 */
export interface ImportsAbsenceBatchCreateResponseData {
    /**
     * 
     * @type {string}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {ImportsAbsenceBatchCreateResponseDataReport}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'report'?: ImportsAbsenceBatchCreateResponseDataReport;
    /**
     * 
     * @type {string}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'generatedAt'?: string;
    /**
     * 0 = Pending  10 = Started  20 = Finished  100 = Failed 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'status'?: ImportsAbsenceBatchCreateResponseDataStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'lineTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'testErrorTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'totalStep'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'expectedCreationTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'expectedUpdateTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'testNonBlockingErrorTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'currentStep'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'creationTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'updateTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportsAbsenceBatchCreateResponseData
     */
    'importErrorTotal'?: number;
}

type ImportsAbsenceBatchCreateResponseDataStatusEnum = 0 | 10 | 20 | 100


