/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ImportsReplaceEntitlementsRequest
 */
export interface ImportsReplaceEntitlementsRequest {
    /**
     * 
     * @type {string}
     * @memberof ImportsReplaceEntitlementsRequest
     */
    'File'?: string;
    /**
     * Description of the entries generated by the import (visible to users in the account details).
     * @type {string}
     * @memberof ImportsReplaceEntitlementsRequest
     */
    'Description'?: string;
    /**
     * Reference date (text mode). Respect the format: yyyy-MM-ddThh: mm: ss
     * @type {string}
     * @memberof ImportsReplaceEntitlementsRequest
     */
    'ReferenceDate'?: string;
    /**
     * Types of entries to take into account, separated by commas, from the following list: AutoAccruals, ManualAccruals, Regularisations, EntitlementsImport, Seniority, Fractionnement, TimeSavings, Comp  By default: `AutoAccruals, ManualAccruals, Regularizations` which correspond to the main cases of acquisition (automatic acquisition, manual adjustments, regularisations).
     * @type {string}
     * @memberof ImportsReplaceEntitlementsRequest
     */
    'EntryTypes'?: string;
}

