/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ImportsCreateAbsencesBatchResponse
 */
export interface ImportsCreateAbsencesBatchResponse {
    /**
     * 
     * @type {string}
     * @memberof ImportsCreateAbsencesBatchResponse
     */
    'summaryId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ImportsCreateAbsencesBatchResponse
     */
    'hasError'?: boolean;
}

