/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ImportsEntitlementsBatchImportResponse
 */
export interface ImportsEntitlementsBatchImportResponse {
    /**
     * 
     * @type {number}
     * @memberof ImportsEntitlementsBatchImportResponse
     */
    'successLinesCount'?: number;
    /**
     * 
     * @type {object}
     * @memberof ImportsEntitlementsBatchImportResponse
     */
    'globalErrors'?: object;
    /**
     * 
     * @type {object}
     * @memberof ImportsEntitlementsBatchImportResponse
     */
    'lineErrors'?: object;
}

