/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ImportsImportLeaveEntitlementsRequest
 */
export interface ImportsImportLeaveEntitlementsRequest {
    /**
     * 
     * @type {string}
     * @memberof ImportsImportLeaveEntitlementsRequest
     */
    'File'?: string;
    /**
     * Description of the entries generated by the import (visible to users in the account details).
     * @type {string}
     * @memberof ImportsImportLeaveEntitlementsRequest
     */
    'Description'?: string;
    /**
     * Reference date (text mode). Respect the format: yyyy-MM-ddThh: mm: ss
     * @type {string}
     * @memberof ImportsImportLeaveEntitlementsRequest
     */
    'ReferenceDate'?: string;
}

