/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ImportsAbsenceBatchCreateResponseDataReport
 */
export interface ImportsAbsenceBatchCreateResponseDataReport {
    /**
     * 
     * @type {string}
     * @memberof ImportsAbsenceBatchCreateResponseDataReport
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ImportsAbsenceBatchCreateResponseDataReport
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ImportsAbsenceBatchCreateResponseDataReport
     */
    'url'?: string;
}

