/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LeaveRequest } from './leave-request';

/**
 * 
 * @export
 * @interface LeaveRequestsListResponseData
 */
export interface LeaveRequestsListResponseData {
    /**
     * 
     * @type {Array<LeaveRequest>}
     * @memberof LeaveRequestsListResponseData
     */
    'items'?: Array<LeaveRequest>;
    /**
     * 
     * @type {number}
     * @memberof LeaveRequestsListResponseData
     */
    'count'?: number;
}

