/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Leave } from './leave';
import { LeavePeriodLog } from './leave-period-log';

/**
 * Absences from work, wether they are planned or not, are described in Lucca using three concepts : **LeaveRequests**, **LeavePeriods** and **Leaves**.  A **LeaveRequest** represent the request made by employees when planning time off. This resource is used for workflow purposes.  A **LeavePeriod** is the continuous period of absence requested by the employee or entered by HR. It is linked to a **LeaveRequest** if workflow applies.  A **Leave** is the subdivision of a **LeavePeriod**. There is one **Leave** per half-day of the **LeavePeriod**. Each **Leave** is linked to a **LeaveAccount**, which represent the type of leave (PTO, Sick Leave, Congés payés, RTT, etc).   ![Timmi Absences - UML](../assets/images/ROunRiCm34LtdeB8M206UeCucG9qABfq9aIs5Y9BBKNPGv6xrrOSH4CcKG-F_F-GZTJA621VVFmXfH5Te9pn3n2Fv2xVcahaKmf9yNFm9YjFog8tTWoBjB1UDSqjkZOd1ueygpUJYAP5OF0iwBow80XmItmJckH3VejaWpK-hE1Tr2S-y_BFHbRoCdHT1zTsRRFgLfgZQFLzFgNuvNKKVhfKTIQJwlRZFR9tBfLePtxIOQ9G.png)  ## Fields
 * @export
 * @interface LeavePeriod
 */
export interface LeavePeriod {
    /**
     * Unique identifier for the LeavePeriod
     * @type {number}
     * @memberof LeavePeriod
     */
    'id'?: number;
    /**
     * Unique identifier for the user 
     * @type {number}
     * @memberof LeavePeriod
     */
    'ownerId'?: number;
    /**
     * Has the value `true` for approved LeavePeriod or the value `false` for LeavePeriod pending approval
     * @type {boolean}
     * @memberof LeavePeriod
     */
    'isConfirmed'?: boolean;
    /**
     * Time at which the LeavePeriod was approved
     * @type {any}
     * @memberof LeavePeriod
     */
    'confirmationDate'?: any;
    /**
     * Unique identifier for the attached document
     * @type {any}
     * @memberof LeavePeriod
     */
    'attachmentId'?: any;
    /**
     * 
     * @type {Array<Leave>}
     * @memberof LeavePeriod
     */
    'leaves'?: Array<Leave>;
    /**
     * 
     * @type {Array<LeavePeriodLog>}
     * @memberof LeavePeriod
     */
    'logs'?: Array<LeavePeriodLog>;
}

