/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * ## Fields
 * @export
 * @interface LeavePeriodLog
 */
export interface LeavePeriodLog {
    /**
     * 
     * @type {number}
     * @memberof LeavePeriodLog
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof LeavePeriodLog
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof LeavePeriodLog
     */
    'comment'?: string;
    /**
     * - 0 = PENDING_APPROVAL - 2 = APPROVED - 3 = DENIED - 4 = CANCELLED - 5 = CANCELLATION_PENDING 
     * @type {number}
     * @memberof LeavePeriodLog
     */
    'status'?: LeavePeriodLogStatusEnum;
}

type LeavePeriodLogStatusEnum = 0 | 2 | 3 | 4 | 5


