/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * **LeaveAccounts** are the type of absences that can be selected by the user   ## Fields
 * @export
 * @interface LeaveAccount
 */
export interface LeaveAccount {
    /**
     * Unique identifier for the LeaveAccount
     * @type {number}
     * @memberof LeaveAccount
     */
    'id'?: number;
    /**
     * Name of the LeaveAccount
     * @type {string}
     * @memberof LeaveAccount
     */
    'name'?: string;
}

