/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Leave } from './leave';

/**
 * 
 * @export
 * @interface LeavesGetApprovedListResponse
 */
export interface LeavesGetApprovedListResponse {
    /**
     * 
     * @type {Leave}
     * @memberof LeavesGetApprovedListResponse
     */
    'data'?: Leave;
}

