/*
Timmi Absences API

Welcome on the documentation for Timmi Absences API.

The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LeaveRequestsApproveDenyRequest
 */
export interface LeaveRequestsApproveDenyRequest {
    /**
     * 
     * @type {boolean}
     * @memberof LeaveRequestsApproveDenyRequest
     */
    'approved'?: boolean;
    /**
     * 
     * @type {any}
     * @memberof LeaveRequestsApproveDenyRequest
     */
    'comment'?: any;
}

